package org.reflection;

import org.main.Config;

import java.lang.reflect.Field;
import java.lang.reflect.Method;

/**
 * TypeFilter Responsibilities:
 * - Class filtering
 *   - Ignore classes that are matched by config.isIgnored(fqcn)
 *   - Ignore classes that are synthetic / anonymous / local (compiler-generated)
 * - Member filtering (fields/methods)
 *   - skip members if their declaring class is ignored
 */
public class TypeFilter {

    TypeFilter() {}

    public boolean isClassOk(Class<?> cls, Config config) {
        if (cls == null) return false;

        String fqcn = cls.getName();

        if (config.isFqcnIgnored(fqcn)) return false;
        if (cls.isSynthetic()) return false; // synthetic class is generated by compiler
        if (cls.isAnonymousClass()) return false; // class with no name declared inline
        if (cls.isLocalClass()) return false; // class declared inside a method

        return true;
    }

    public boolean isMethodOk(Method method, Config config) {
        if (method == null) return false;
        if (config.isFqcnIgnored(method.getDeclaringClass().getName())) return false;
        if (method.isSynthetic()) return false; // // compiler generated method
        if (method.isBridge()) return false; // compiler generated method to preserve polymorphism after type erasure

        return true;
    }

    public boolean isFieldOk(Field field, Config config) {
        if (field == null) { return false;}
        if (config.isFqcnIgnored(field.getDeclaringClass().getName())) return false;

        return true;
    }
}
